version: "3.7"
name: kafka-cluster

services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - "9095:9095" # Exposes Kafka to localhost
    environment:
      # General KRaft configuration
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: 'broker, controller'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '0@kafka:9093'

      # Listener configuration
      KAFKA_CFG_LISTENERS: 'BROKER://:9092,CONTROLLER://:9093,INTERNAL://:9094,EXTERNAL://:9095'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'

      # Advertised listeners for internal and external clients
      KAFKA_CFG_ADVERTISED_LISTENERS: 'BROKER://kafka:9092,EXTERNAL://localhost:9095,INTERNAL://kafka:9094'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'BROKER'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CLIENT_LISTENER_NAME: 'INTERNAL' # Listener for internal Bitnami scripts
    volumes:
      - 'kafka-data:/bitnami/kafka'
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server kafka:9092 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - inner-cluster-communication

  kafka-ui:
    image: 'ghcr.io/kafbat/kafka-ui:latest'
    container_name: kafka-ui
    ports:
      - '8080:8080'
    restart: always
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9094'
    networks:
      - inner-cluster-communication
    depends_on:
      kafka:
        condition: service_healthy

networks:
  inner-cluster-communication:

volumes:
  kafka-data:
