version: "3.7"
name: streaming-cluster

services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - "9095:9095"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: 'broker, controller'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '0@kafka:9093'

      KAFKA_CFG_LISTENERS: 'BROKER://:9092,CONTROLLER://:9093,INTERNAL://:9094,EXTERNAL://:9095'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'

      KAFKA_CFG_ADVERTISED_LISTENERS: 'BROKER://kafka:9092,EXTERNAL://localhost:9095,INTERNAL://kafka:9094'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'BROKER'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CLIENT_LISTENER_NAME: 'INTERNAL'
    volumes:
      - 'kafka-data:/bitnami/kafka'
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server kafka:9092 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - inner-cluster-communication

  kafka-ui:
    image: 'ghcr.io/kafbat/kafka-ui:latest'
    container_name: kafka-ui
    ports:
      - '8080:8080'
    restart: unless-stopped
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9094'
    networks:
      - inner-cluster-communication
    depends_on:
      kafka:
        condition: service_healthy

  jobmanager:
    image: 'flink:2.0.0-scala_2.12-java11'
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./volumes/flink-usrlib:/opt/flink/usrlib
    networks:
      - inner-cluster-communication
    depends_on:
      kafka:
        condition: service_healthy

  taskmanager:
    image: 'flink:2.0.0-scala_2.12-java11'
    container_name: taskmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - inner-cluster-communication
    depends_on:
      - jobmanager

networks:
  inner-cluster-communication:

volumes:
  kafka-data:
